// A curated, massive list of trending words across various cultures (GenZ, Crypto, Tech, Corporate, Pop Culture)
final List<String> trendingWords = [
  'Exit Liquidity',
  'Diamond Hands',
  'Rug Pull',
  'FOMO',
  'FUD',
  'Rizz',
  'Touch Grass',
  'Gaslight',
  'Gatekeep',
  'Girlboss',
  'Main Character Energy',
  'Quiet Quitting',
  'Bare Minimum Monday',
  'W rizz',
  'L rizz',
  'Based',
  'Cringe',
  'Cap',
  'No Cap',
  'Slaps',
  'Bops',
  'Rent Free',
  'Vibe Check',
  'It\'s giving',
  'Understood the assignment',
  'Situationship',
  'Ghosting',
  'Breadcrumbing',
  'Orbiting',
  'Love Bombing',
  'Soft Launch',
  'Hard Launch',
  'Nepo Baby',
  'Menty B',
  'Delulu',
  'Solulu',
  'Roman Empire',
  'Girl Dinner',
  'Boy Math',
  'Girl Math',
  'Canon Event',
  'Lore',
  'NPC',
  'Buff',
  'Nerf',
  'Skill Issue',
  'Git Gud',
  'Smurf',
  'Sweat',
  'Tryhard',
  'AFK',
  'IRL',
  'IYKYK',
  'TBH',
  'NGL',
  'SMH',
  'TL;DR',
  'Circle Back',
  'Synergy',
  'Bandwidth',
  'Deep Dive',
  'Low-Hanging Fruit',
  'Moving the Goalposts',
  'Paradigm Shift',
  'Boil the Ocean',
  'Pivot',
  'Disrupt',
  'Unicorn',
  'Decacorn',
  'Bootstrapping',
  'Burn Rate',
  'Runway',
  'Hockey Stick Growth',
  'MVP',
  'SaaS',
  'B2B',
  'B2C',
  'Web3',
  'Metaverse',
  'NFT',
  'DeFi',
  'DAO',
  'Smart Contract',
  'Blockchain',
  'HODL',
  'To the Moon',
  'Whale',
  'Bear Market',
  'Bull Market',
  'Altcoin',
  'Shitcoin',
  'Ape In',
  'Degen',
  'WAGMI',
  'NGMI',
  'DYOR',
  'Paper Hands',
  'Buy the Dip',
  'Dead Cat Bounce',
  'Fiat',
  'Gas Fees',
  'Mint',
  'Staking',
  'Yield Farming',
  'Alpha',
  'Beta',
  'Sigma',
  'Chad',
  'Gigachad',
  'Simp',
  'Incel',
  'Red Pill',
  'Blue Pill',
  'Black Pill',
  'Copium',
  'Hopium',
  'Ratio',
  'L',
  'W',
  'Mid',
  'Aesthetic',
  'Core',
  'Era',
  'Stan',
  'Sksksk',
  'Oof',
  'Yeet',
  'Sus',
  'Amogus',
  'Salty',
  'Tea',
  'Shade',
  'Receipts',
  'Cancel Culture',
  'Woke',
  'Snowflake',
  'Boomer',
  'Zoomer',
  'Millennial',
  'Gen X',
  'Gen Z',
  'Gen Alpha',
  'Karen',
  'Chad',
  'Stacy',
  'Becky',
  'Kyle',
  'YOLO',
  'GOAT',
  'Glow Up',
  'Flex',
  'Drip',
  'Clout',
  'Bussin',
  'Sheesh',
  'Bet',
  'Facts',
  'Periodt',
  'Purr',
  'Slay',
  'Yassify',
  'Camp',
  'Cheugy',
  'Basic',
  'Extra',
  'Gucci',
  'Bougie',
  'Ratchet',
  'Ghetto',
  'Hood',
  'Ops',
  'Trap',
  'Drill',
  'Grime',
  'Mumble Rap',
  'SoundCloud Rapper',
  'Industry Plant',
  'Nepotism',
  'Gas',
  'Fire',
  'Trash',
  'Dumpster Fire',
  'Trainwreck',
  'Shitshow',
  'Clusterfuck',
  'FUBAR',
  'SNAFU',
  'AWOL',
  'MIA',
  'DOA',
  'RIP',
  'GG',
  'WP',
  'GLHF',
  'BRB',
  'BRT',
  'ETA',
  'TBD',
  'TBA',
  'FYI',
  'PSA',
  'ASAP',
  'RSVP',
  'DIY',
  'FAQ',
  'AMA',
  'TIL',
  'ELI5',
  'YMMV',
  'IIRC',
  'AFAIK',
  'IMHO',
  'TBH',
  'TMI',
  'NSFW',
  'NSFL',
  'SFW',
  'Trigger Warning',
  'Content Warning',
  'Safe Space',
  'Echo Chamber',
  'Filter Bubble',
  'Doomscrolling',
  'Phubbing',
  'Catfishing',
  'Troll',
  'Bot',
  'Shill',
  'Astroturfing',
  'Clickbait',
  'Ragebait',
  'Engagement Bait',
  'Ratioed',
  'Shadowban',
  'Deplatform',
  'Doxxing',
  'Swatting',
  'Brigading',
  'Review Bombing',
  'Simping',
  'Thirst Trap',
  'Reply Guy',
  'Pick Me Girl',
  'Soft Boy',
  'E-Girl',
  'E-Boy',
  'V-Tuber',
  'Streamer',
  'Influencer',
  'Content Creator',
  'Micro-Influencer',
  'Brand Ambassador',
  'Sponsor',
  'Ad',
  'Collab',
  'Giveaway',
  'Merch',
  'Drop',
  'Cop',
  'Reseller',
  'Scalper',
  'Hypebeast',
  'Sneakerhead',
  'Grail',
  'Deadstock',
  'Fake',
  'Rep',
  'Bootleg',
  'Knockoff',
  'Dupe',
  'Aesthetic',
  'Vibe',
  'Mood',
  'Energy',
  'Aura',
  'Manifesting',
  'Law of Attraction',
  'Astrology',
  'Zodiac',
  'Tarot',
  'Crystals',
  'WitchTok',
  'Cottagecore',
  'Dark Academia',
  'Light Academia',
  'Y2K',
  'Cyberpunk',
  'Steampunk',
  'Vaporwave',
  'Synthwave',
  'Lo-Fi',
  'Chillhop',
  'ASMR',
  'Mukbang',
  'Unboxing',
  'Haul',
  'Vlog',
  'Podcast',
  'Livestream',
  'Speedrun',
  'Let\'s Play',
  'Walkthrough',
  'Tutorial',
  'Lifehack',
  'DIY',
  'Crafts',
  'Art',
  'Design',
  'Architecture',
  'Photography',
  'Videography',
  'Cinematography',
  'Editing',
  'Color Grading',
  'Sound Design',
  'VFX',
  'CGI',
  'Animation',
  'Motion Graphics',
  'Illustration',
  'Typography',
  'Branding',
  'Marketing',
  'Advertising',
  'PR',
  'SEO',
  'SEM',
  'SMM',
  'Content Strategy',
  'Copywriting',
  'UX',
  'UI',
  'Web Design',
  'App Development',
  'Software Engineering',
  'Data Science',
  'Machine Learning',
  'AI',
  'Deep Learning',
  'Neural Network',
  'Algorithm',
  'Code',
  'Bug',
  'Feature',
  'Patch',
  'Update',
  'Version',
  'Release',
  'Beta',
  'Alpha',
  'Early Access',
  'Open Source',
  'Proprietary',
  'Freemium',
  'Subscription',
  'Microtransaction',
  'Loot Box',
  'Pay to Win',
  'Free to Play',
  'Indie',
  'AAA',
  'Console',
  'PC',
  'Mobile',
  'Cloud Gaming',
  'VR',
  'AR',
  'MR',
  'XR',
  'Haptics',
  'Biometrics',
  'Wearables',
  'IoT',
  'Smart Home',
  'Smart City',
  'Autonomous Vehicle',
  'Drone',
  'Robotics',
  '3D Printing',
  'Nanotechnology',
  'Biotechnology',
  'CRISPR',
  'Gene Editing',
  'Synthetic Biology',
  'Quantum Computing',
  'Fusion Energy',
  'Renewable Energy',
  'Climate Change',
  'Sustainability',
  'ESG',
  'Carbon Footprint',
  'Net Zero',
  'Greenwashing',
  'Circular Economy',
  'Upcycling',
  'Zero Waste',
  'Minimalism',
  'Veganism',
  'Plant-Based',
  'Cruelty-Free',
  'Organic',
  'Non-GMO',
  'Gluten-Free',
  'Keto',
  'Paleo',
  'Intermittent Fasting',
  'Biohacking',
  'Nootropics',
  'Microdosing',
  'Psychedelics',
  'Mindfulness',
  'Meditation',
  'Yoga',
  'Pilates',
  'CrossFit',
  'HIIT',
  'Marathon',
  'Triathlon',
  'Ironman',
  'Olympics',
  'World Cup',
  'Super Bowl',
  'Esports',
  'Fantasy Sports',
  'Sports Betting',
  'Poker',
  'Casino',
  'Lottery',
  'Crypto',
  'Bitcoin',
  'Ethereum',
  'Dogecoin',
  'Shiba Inu',
  'Pepe',
  'Meme Coin',
  'Stablecoin',
  'CBDC',
  'Fiat',
  'Inflation',
  'Deflation',
  'Recession',
  'Depression',
  'Bull Market',
  'Bear Market',
  'Stock Market',
  'Wall Street',
  'Main Street',
  'Silicon Valley',
  'Hollywood',
  'Bollywood',
  'Nollywood',
  'K-Pop',
  'J-Pop',
  'Anime',
  'Manga',
  'Webtoon',
  'Manhwa',
  'Comic',
  'Graphic Novel',
  'Superhero',
  'Villain',
  'Antihero',
  'Sidekick',
  'Trope',
  'Cliche',
  'Stereotype',
  'Archetype',
  'Protagonist',
  'Antagonist',
  'Plot Armor',
  'Deus Ex Machina',
  'MacGuffin',
  'Red Herring',
  'Foreshadowing',
  'Flashback',
  'Flashforward',
  'Cliffhanger',
  'Spoiler',
  'Easter Egg',
  'Cameo',
  'Crossover',
  'Spin-off',
  'Reboot',
  'Remake',
  'Sequel',
  'Prequel',
  'Trilogy',
  'Franchise',
  'Cinematic Universe',
  'Fandom',
  'Ship',
  'OTP',
  'Headcanon',
  'Fanfic',
  'Cosplay',
  'Convention',
  'Geek',
  'Nerd',
  'Dork',
  'Weeb',
  'Otaku',
  'Koreaboo',
  'Gamer',
  'Noob',
  'Pro',
  'Hacker',
  'Cracker',
  'Phisher',
  'Scammer',
  'Grifter',
  'Hustler',
  'Entrepreneur',
  'Solopreneur',
  'Freelancer',
  'Digital Nomad',
  'Remote Work',
  'WFH',
  'Hybrid Work',
  'Return to Office',
  'RTO',
  'Great Resignation',
  'Quiet Quitting',
  'Layoff',
  'Furlough',
  'Severance',
  'Unemployment',
  'Universal Basic Income',
  'UBI',
  'Gig Economy',
  'Side Hustle',
  'Passive Income',
  'FIRE',
  'Financial Independence',
  'Retire Early',
  'Hustle Culture',
  'Grindset',
  'Toxic Positivity',
  'Gaslighting',
  'Gatekeeping',
  'Girlbossing',
  'Mansplaining',
  'Manspreading',
  'Hepeating',
  'Microaggression',
  'Implicit Bias',
  'Privilege',
  'Intersectionality',
  'Allyship',
  'Performative Activism',
  'Virtue Signaling',
  'Cancel Culture',
  'Call Out Culture',
  'Accountability',
  'Restorative Justice',
  'Systemic Racism',
  'Institutional Racism',
  'Colorism',
  'Featurism',
  'Texturism',
  'Ageism',
  'Ableism',
  'Classism',
  'Sexism',
  'Misogyny',
  'Misandry',
  'Patriarchy',
  'Matriarchy',
  'Feminism',
  'Men\'s Rights',
  'MRA',
  'Incel',
  'Volcel',
  'MGTOW',
  'Pick Up Artist',
  'PUA',
  'Alpha Male',
  'Beta Male',
  'Sigma Male',
  'High Value Man',
  'High Value Woman',
  'TradWife',
  'Stay at Home Mom',
  'SAHM',
  'Working Mom',
  'Mommy Blogger',
  'Family Vlogger',
  'Child Exploitation',
  'Sharenting',
  'Helicopter Parent',
  'Tiger Mom',
  'Gentle Parenting',
  'Attachment Parenting',
  'Free Range Parenting',
  'Unschooling',
  'Homeschooling',
  'Public School',
  'Private School',
  'Charter School',
  'Ivy League',
  'HBCU',
  'Community College',
  'Trade School',
  'Student Debt',
  'Forgiveness',
  'Gap Year',
  'Study Abroad',
  'Backpacking',
  'Hostel',
  'Couchsurfing',
  'Airbnb',
  'Uber',
  'Lyft',
  'Doordash',
  'UberEats',
  'Postmates',
  'Instacart',
  'TaskRabbit',
  'Fiverr',
  'Upwork',
  'Patreon',
  'OnlyFans',
  'Substack',
  'Medium',
  'Twitter',
  'X',
  'Facebook',
  'Instagram',
  'Threads',
  'TikTok',
  'Snapchat',
  'Pinterest',
  'LinkedIn',
  'Reddit',
  'Discord',
  'Twitch',
  'YouTube',
  'Vimeo',
  'Netflix',
  'Hulu',
  'Amazon Prime',
  'Disney+',
  'HBO Max',
  'Apple TV+',
  'Peacock',
  'Paramount+',
  'Spotify',
  'Apple Music',
  'SoundCloud',
  'Tidal',
  'Pandora',
  'SiriusXM',
  'Podcast',
  'Audiobook',
  'Kindle',
  'Nook',
  'Goodreads',
  'Wattpad',
  'AO3',
  'Tumblr',
  'Blogger',
  'WordPress',
  'Squarespace',
  'Wix',
  'Shopify',
  'Etsy',
  'Amazon',
  'eBay',
  'Craigslist',
  'Facebook Marketplace',
  'Depop',
  'Poshmark',
  'Mercari',
  'Thrifting',
  'Vintage',
  'Y2K',
  'Fast Fashion',
  'Haute Couture',
  'Streetwear',
  'Athleisure',
  'Loungewear',
  'Business Casual',
  'Black Tie',
  'White Tie',
  'Cocktail',
  'Smart Casual',
  'Normcore',
  'Gorpcore',
  'Cottagecore',
  'Dark Academia',
];
